### ISSUE TITLE
Facing issue while building using "mvn clean install" command:- [FATAL] Non-resolvable parent POM for org.eclipse.che:che-bookmark-plugin-parent:0.1.0-SNAPSHOT

### ISSUE THREAD

**Issue by Rahith-RR** [vzhukovskii/che-gradle-plugin#1]
**I am using online IDE of eclipse che.
Below is the issue that i am facing while trying to build the project:-**

**bash-5.0 /projects/che-bookmark-plugin $ mvn clean install**
Picked up JAVA_TOOL_OPTIONS: -XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom
[INFO] Scanning for projects...
Downloading from codenvy-public-repo: https://maven.codenvycorp.com/content/groups/public/org/eclipse/che/depmgt/maven-depmgt-pom/5.0.0-M5-SNAPSHOT/maven-metadata.xml
Downloading from codenvy-public-snapshots-repo: https://maven.codenvycorp.com/content/repositories/codenvy-public-snapshots/org/eclipse/che/depmgt/maven-depmgt-pom/5.0.0-M5-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata org.eclipse.che.depmgt:maven-depmgt-pom:5.0.0-M5-SNAPSHOT/maven-metadata.xml from/to codenvy-public-repo (https://maven.codenvycorp.com/content/groups/public/): Transfer failed for https://maven.codenvycorp.com/content/groups/public/org/eclipse/che/depmgt/maven-depmgt-pom/5.0.0-M5-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata org.eclipse.che.depmgt:maven-depmgt-pom:5.0.0-M5-SNAPSHOT/maven-metadata.xml from/to codenvy-public-snapshots-repo (https://maven.codenvycorp.com/content/repositories/codenvy-public-snapshots/): Transfer failed for https://maven.codenvycorp.com/content/repositories/codenvy-public-snapshots/org/eclipse/che/depmgt/maven-depmgt-pom/5.0.0-M5-SNAPSHOT/maven-metadata.xml
Downloading from codenvy-public-repo: https://maven.codenvycorp.com/content/groups/public/org/eclipse/che/depmgt/maven-depmgt-pom/5.0.0-M5-SNAPSHOT/maven-depmgt-pom-5.0.0-M5-SNAPSHOT.pom
Downloading from codenvy-public-snapshots-repo: https://maven.codenvycorp.com/content/repositories/codenvy-public-snapshots/org/eclipse/che/depmgt/maven-depmgt-pom/5.0.0-M5-SNAPSHOT/maven-depmgt-pom-5.0.0-M5-SNAPSHOT.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.eclipse.che:che-bookmark-plugin-parent:0.1.0-SNAPSHOT: Could not transfer artifact org.eclipse.che.depmgt:maven-depmgt-pom:pom:5.0.0-M5-SNAPSHOT from/to codenvy-public-repo (https://maven.codenvycorp.com/content/groups/public/): Transfer failed for https://maven.codenvycorp.com/content/groups/public/org/eclipse/che/depmgt/maven-depmgt-pom/5.0.0-M5-SNAPSHOT/maven-depmgt-pom-5.0.0-M5-SNAPSHOT.pom and 'parent.relativePath' points at wrong local POM @ line 16, column 13
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.eclipse.che:che-bookmark-plugin-parent:0.1.0-SNAPSHOT (/projects/che-bookmark-plugin/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.eclipse.che:che-bookmark-plugin-parent:0.1.0-SNAPSHOT: Could not transfer artifact org.eclipse.che.depmgt:maven-depmgt-pom:pom:5.0.0-M5-SNAPSHOT from/to codenvy-public-repo (https://maven.codenvycorp.com/content/groups/public/): Transfer failed for https://maven.codenvycorp.com/content/groups/public/org/eclipse/che/depmgt/maven-depmgt-pom/5.0.0-M5-SNAPSHOT/maven-depmgt-pom-5.0.0-M5-SNAPSHOT.pom and 'parent.relativePath' points at wrong local POM @ line 16, column 13: Connect to maven.codenvycorp.com:443 [maven.codenvycorp.com/54.235.115.153] failed: Connection timed out (Connection timed out) -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by vzhukovskii** [comment]
I suppose, that https://maven.codenvycorp.com/ repository has been already shutdown. It was our old maven repository. And not sure, that che 5 is possible to build nowadays because it is not supported now. What can I propose is to move to che 7. 

https://github.com/eclipse/che
